### ISSUE TITLE
Staff Request

### ISSUE THREAD

**Issue by manahan-joseph** [bendude56/GoldenApple#16]
Sometimes when an admin/mod is busy, it's hard to get a hold of them for their help and often will remember you need help. So how about a command to get in line for a staff members help. For example 

/request (type of help required, i.e: Lot~Griefing~Other) (Description)

And then returns their number in line, as to minimize repetitive (and annoying) calls for help.
If a moderator is able to preform the needed task, then the request is assigned to a moderator. If a moderator is unable to preform the task, then it assigns the task to an Admin....ect.

**Comment by charliebobgordon** [comment]
I just manage the website mainly, but I'm primarily a designer so I'm looking for a volunteer to help with the functional side of things. Wanna email me and let me know what your level of expertise is?
